# Generated by Django 2.2 on 2021-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_released',
            field=models.CharField(max_length=255),
        ),
    ]
