# Generated by Django 2.2 on 2021-09-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20210906_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_released',
            field=models.IntegerField(),
        ),
    ]
